language: python
python:
  - "3.6"
  - "nightly"

cache: pip

addons:
  postgresql: "9.6"

service:
  - redis-server

install:
- pip install pytest-cov pytest-django flake8 -r requirements.txt

script: pytest --cov=.

after_success: codecov
