language: python
python:
  - "3.6"
  - "nightly"

cache: pip

addons:
  postgresql: "9.6"

services:
  - redis-server

install:
- pip install prequ
- prequ sync requirements-dev.txt requirements.txt

script: pytest --cov=.

after_success: codecov
