# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_agent', models.TextField(blank=True, max_length=400, null=True, verbose_name="The user agent string of the user's browser")),
                ('rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4)], null=True, verbose_name='Rating')),
                ('body', models.TextField(blank=True, verbose_name='Body')),
                ('url', models.URLField(verbose_name='URL of page where feedback was sent from')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Notifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('slack', 'Slack')], max_length=20)),
                ('url_base', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SlackNotifier',
            fields=[
                ('notifier_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='feedback.Notifier')),
                ('webhook_url', models.URLField()),
                ('channel', models.CharField(blank=True, max_length=50, null=True)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('icon_emoji', models.CharField(blank=True, max_length=50, null=True)),
                ('icon_url', models.URLField(blank=True, null=True)),
            ],
            bases=('feedback.notifier',),
        ),
    ]
